# Generated by Django 5.1.4 on 2025-01-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_announcement_user_image_announcement_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
