# Generated by Django 5.1.4 on 2025-01-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_announcement_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
    ]
