# Generated by Django 5.1.4 on 2025-01-07 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('leave_balance', models.FloatField(default=2.0)),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('user_id', models.IntegerField()),
                ('notes', models.TextField(null=True)),
                ('avail_permission', models.FloatField(default=0.0)),
                ('session', models.CharField(max_length=20, null=True)),
                ('duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Permission Request',
                'verbose_name_plural': 'Permission Requests',
            },
        ),
    ]
