# Generated by Django 5.1.5 on 2025-01-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='user_department',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
