# Generated by Django 5.1.4 on 2025-01-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=10)),
                ('day', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
