# Generated by Django 5.1.4 on 2025-01-07 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_user_id', models.CharField(max_length=200)),
                ('Salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_first_name', models.CharField(max_length=200)),
                ('employee_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('zip', models.CharField(blank=True, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('marital_status', models.CharField(max_length=50)),
                ('Workstream', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=20, null=True)),
                ('departmant', models.CharField(max_length=100, null=True)),
                ('designation', models.CharField(max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportees', to='employees.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Work Anniversary', 'Work Anniversary')], max_length=50)),
                ('event_date', models.DateField()),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_photo', models.ImageField(blank=True, null=True, upload_to='event_photos/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='employees.employee')),
            ],
        ),
    ]
