# Generated by Django 5.1.4 on 2025-01-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
